services:
    _defaults:
        autowire: true
        autoconfigure: true

    Devbanana\YnabTools\Tests\Acceptance\:
        resource: '../tests/Acceptance/*'

    Devbanana\YnabTools\Domain\Contract\Model\User\UserRepositoryInterface: '@Devbanana\YnabTools\Tests\Acceptance\UserRepositoryStub'
